import { Club, ClubMeetingFrequency } from "../types/club";

export const SAMPLE_CLUBS: Club[] = [
  {
    id: "1",
    name: "Sunrise Toastmasters",
    description:
      "A vibrant community of speakers and leaders dedicated to improving communication and leadership skills.",
    district: "District 41",
    area: "Area 12",
    division: "Division B",
    ownerId: "user-1",
    meetingFrequency: ClubMeetingFrequency.WEEKLY,
    clubCode: "TM-2024-001",
    members: [],
    createdAt: "2024-01-01",
    updatedAt: "2024-12-01",
  },
  {
    id: "2",
    name: "Downtown Speakers",
    description:
      "Where professionals come to sharpen their public speaking and leadership abilities.",
    district: "District 41",
    area: "Area 15",
    division: "Division A",
    ownerId: "user-2",
    meetingFrequency: ClubMeetingFrequency.BIWEEKLY,
    clubCode: "TM-2024-002",
    members: [],
    createdAt: "2024-02-15",
    updatedAt: "2024-11-20",
  },
  {
    id: "3",
    name: "Tech Talkers Club",
    description:
      "A club for tech enthusiasts who want to improve their presentation and communication skills.",
    district: "District 42",
    area: "Area 8",
    division: "Division C",
    ownerId: "user-3",
    meetingFrequency: ClubMeetingFrequency.WEEKLY,
    clubCode: "TM-2024-003",
    members: [],
    createdAt: "2024-03-10",
    updatedAt: "2024-12-05",
  },
  {
    id: "4",
    name: "Evening Excellence",
    description:
      "Perfect for working professionals who want to develop their skills after work hours.",
    district: "District 41",
    area: "Area 12",
    division: "Division B",
    ownerId: "user-4",
    meetingFrequency: ClubMeetingFrequency.WEEKLY,
    clubCode: "TM-2024-004",
    members: [],
    createdAt: "2024-04-20",
    updatedAt: "2024-12-01",
  },
  {
    id: "5",
    name: "Leadership Legends",
    description:
      "Focused on developing strong leadership skills through practice and mentorship.",
    district: "District 43",
    area: "Area 5",
    division: "Division D",
    ownerId: "user-5",
    meetingFrequency: ClubMeetingFrequency.MONTHLY,
    clubCode: "TM-2024-005",
    members: [],
    createdAt: "2024-05-01",
    updatedAt: "2024-11-15",
  },
  {
    id: "6",
    name: "Weekend Warriors",
    description:
      "For those who prefer weekend meetings to hone their public speaking craft.",
    district: "District 41",
    area: "Area 20",
    division: "Division E",
    ownerId: "user-6",
    meetingFrequency: ClubMeetingFrequency.BIWEEKLY,
    clubCode: "TM-2024-006",
    members: [],
    createdAt: "2024-06-12",
    updatedAt: "2024-12-08",
  },
];
